name: Test Mock API

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22

            - name: Install dependencies
              run: npm ci

            - name: Start JSON Server in background
              run: npm run tern-on-api & sleep 5

            - name: Wait for server
              run: npx wait-on http://localhost:3000

            - name: Run Newman tests
              run: npx newman run storeV2_collection.json -r htmlextra --reporter-htmlextra-export reports/store-report.html

            - name: Stop server
              run: npx kill-port 3000

            - name: Upload Newman HTML report
              uses: actions/upload-artifact@v3
              with:
                  name: store-report
                  path: reports/store-report.html
