name: Run Postman Collections

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-newman:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Настраиваем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: npm install

      # 4. Поднимаем мок-сервер в фоне
      - name: Start Mock API
        run: npm run tern-on-api &

      # 5. Ждём, пока сервер будет доступен
      - name: Wait for API
        run: npx wait-on http://localhost:3000

      # 6. Запускаем коллекцию Store
      - name: Run Store Collection
        run: npx newman run storeV2_collection.json -r htmlextra --reporter-htmlextra-export reports/store-report.html

      # 7. Запускаем коллекцию Petstore
      - name: Run Petstore Collection
        run: npx newman run petstore.collection.json -r htmlextra --reporter-htmlextra-export reports/petstore-report.html
