name: Newman Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run store collection
        run: npm run run-tests:store

      - name: Run petstore collection
        run: npm run run-tests:petstore

      - name: Deploy reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
          publish_branch: gh-pages
