name: Run Postman Collections

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Устанавливаем Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # 3️⃣ Устанавливаем зависимости
      - name: Install dependencies
        run: npm install

      # 4️⃣ Устанавливаем cpx и start-server-and-test для кроссплатформенного копирования и ожидания сервера
      - name: Install dev dependencies
        run: npm install --save-dev js-yaml

      # 5️⃣ Запуск сервера и тестов коллекции storeV2
      - name: Run storeV2_collection tests
        run: npm run start-and-test

      # 6️⃣ Запуск тестов коллекции petstore
      - name: Run petstore_collection tests
        run: start-server-and-test 'npm run tern-on-api' http://localhost:3000 'newman run petstore.collection.json -r htmlextra --reporter-htmlextra-export reports/petstore-report.html'

      # 7️⃣ Загрузка отчётов как артефактов
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: newman-reports
          path: reports/
